name: rag-chatbot
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - langchain
      - langchain-community
      - sentence-transformers
      - streamlit
      - openai
      - faiss-cpu
      - unstructured
      - langchain-classic
